import type { AdvisoryAction, CrisisVault, DeltaItem, MarketProbeResult, RiskMatrix } from "../types.js";
import { auditLog } from "./auditLogger.js";

const FREE_TIER_DISCLAIMER =
  "Summary generated by Gemini 3 Flash free tier. Extensive use can exhaust the free quota.";

const QUOTA_REACHED_MESSAGE =
  "Cannot summarize as free quota reached its limit please wait for 24 hours.";

type GeminiOutcome =
  | { kind: "ok"; advisory: AdvisoryAction[] }
  | { kind: "quota"; advisory: AdvisoryAction[] };

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function compactVault(vault: CrisisVault): Array<{
  key: string;
  label: string;
  domain: string;
  recent: Array<{ timestamp: string; price: number; unit: string; source?: string }>;
}> {
  return Object.values(vault.commodities).map((series) => ({
    key: series.key,
    label: series.label,
    domain: series.domain,
    recent: series.entries.slice(-5).map((entry) => ({
      timestamp: entry.timestamp,
      price: entry.price,
      unit: entry.unit,
      source: entry.source
    }))
  }));
}

function buildPrompt(probe: MarketProbeResult, deltas: DeltaItem[], risk: RiskMatrix, vault: CrisisVault): string {
  const payload = {
    objective:
      "Analyze crisis signals using previous local knowledge + latest data and produce one concise summary, one energy precaution, and one food precaution. The food precaution must incorporate fertilizer price signals (Urea and NPK) where available, as they directly impact agricultural input costs and food security.",
    constraints: {
      dateContext: "May 2026 global supply crisis",
      style: "operational, concise, non-alarmist",
      outputLanguage: "English"
    },
    latestProbe: probe,
    deltas,
    risk,
    localKnowledgeRecentHistory: compactVault(vault),
    outputSchema: {
      summary: "string",
      energy_precaution: "string",
      food_precaution: "string"
    }
  };

  return `Return ONLY valid JSON. No markdown.\\n${JSON.stringify(payload)}`;
}

function parseGeminiText(text: string): { summary: string; energy_precaution: string; food_precaution: string } | null {
  try {
    const parsed = JSON.parse(text) as {
      summary?: unknown;
      energy_precaution?: unknown;
      food_precaution?: unknown;
    };

    if (
      typeof parsed.summary === "string" &&
      typeof parsed.energy_precaution === "string" &&
      typeof parsed.food_precaution === "string"
    ) {
      return {
        summary: parsed.summary,
        energy_precaution: parsed.energy_precaution,
        food_precaution: parsed.food_precaution
      };
    }
  } catch {
    // best-effort parse only
  }
  return null;
}

function renderQuotaAdvisory(): AdvisoryAction[] {
  return [
    {
      region: "Precautionary Action Wizard",
      action: "Cannot summarize",
      reason: QUOTA_REACHED_MESSAGE
    },
    {
      region: "Disclaimer",
      action: "Gemini Free Tier",
      reason: FREE_TIER_DISCLAIMER
    }
  ];
}

function renderGeminiAdvisory(parsed: { summary: string; energy_precaution: string; food_precaution: string }): AdvisoryAction[] {
  return [
    {
      region: "Global Summary",
      action: "Situation Update",
      reason: parsed.summary
    },
    {
      region: "Energy",
      action: "Precautionary Measure",
      reason: parsed.energy_precaution
    },
    {
      region: "Food",
      action: "Precautionary Measure",
      reason: parsed.food_precaution
    },
    {
      region: "Disclaimer",
      action: "Gemini Free Tier",
      reason: FREE_TIER_DISCLAIMER
    }
  ];
}

async function callGeminiUntilResolved(prompt: string): Promise<GeminiOutcome> {
  const apiKey = process.env.GEMINI_API_KEY;
  const model = "gemini-3.1-flash-lite-preview";
  const apiVersion = "v1beta";

  if (!apiKey) {
    auditLog("Gemini advisory skipped", { reason: "missing_api_key" });
    return {
      kind: "quota",
      advisory: [
        {
          region: "Precautionary Action Wizard",
          action: "Cannot summarize",
          reason: "Cannot summarize because GEMINI_API_KEY is not configured."
        },
        {
          region: "Disclaimer",
          action: "Gemini Free Tier",
          reason: FREE_TIER_DISCLAIMER
        }
      ]
    };
  }

  let attempt = 0;
  // User requirement: if request fails, wait 1 minute and try again until valid
  // response is obtained, except explicit quota exhaustion.
  while (true) {
    attempt += 1;
    const url = `https://generativelanguage.googleapis.com/${apiVersion}/models/${model}:generateContent`;
    const requestBody: {
      contents: Array<{ role: string; parts: Array<{ text: string }> }>;
      generationConfig?: { responseMimeType: string };
    } = {
      contents: [{ role: "user", parts: [{ text: prompt }] }],
      generationConfig: { responseMimeType: "application/json" }
    };

    auditLog("Gemini advisory request", { attempt, model, apiVersion });
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-goog-api-key": apiKey
      },
      body: JSON.stringify(requestBody)
    });

    const body = await response.text();
    auditLog("Gemini advisory response", { attempt, model, apiVersion, status: response.status, body });

    if (response.status === 429) {
      return { kind: "quota", advisory: renderQuotaAdvisory() };
    }

    if (!response.ok) {
      auditLog("Gemini advisory retryable failure", { attempt, model, apiVersion, status: response.status });
    } else {
      try {
        const payload = JSON.parse(body) as {
          candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }>;
        };
        const text = payload.candidates?.[0]?.content?.parts?.[0]?.text ?? "";
        const parsed = parseGeminiText(text);
        if (parsed) {
          return { kind: "ok", advisory: renderGeminiAdvisory(parsed) };
        }
      } catch {
        // fall through to the timed retry below
      }
    }

    auditLog("Gemini advisory retry scheduled", { attempt, waitSeconds: 60 });
    await sleep(60_000);
  }
}

export async function buildGeminiAdvisoryActions(
  probe: MarketProbeResult,
  deltas: DeltaItem[],
  risk: RiskMatrix,
  vault: CrisisVault,
  fallbackActions: AdvisoryAction[]
): Promise<AdvisoryAction[]> {
  try {
    const prompt = buildPrompt(probe, deltas, risk, vault);
    const outcome = await callGeminiUntilResolved(prompt);
    return outcome.advisory;
  } catch (error) {
    auditLog("Gemini advisory fallback", {
      error: error instanceof Error ? error.message : String(error)
    });

    return [
      ...fallbackActions,
      {
        region: "Disclaimer",
        action: "Gemini Free Tier",
        reason: FREE_TIER_DISCLAIMER
      }
    ];
  }
}
